default : all

run :
	./YUVLoader BasketballPass_416x240_50.yuv 416 240 50 > BasketballPass.out
	./YUVLoader BQMall_832x480_60.yuv 832 480 50 > BQMall.out
	./YUVLoader FourPeople_1280x720_60.yuv 1280 720 50 > FourPeople.out
	./YUVLoader Johnny_1280x720_60.yuv 1280 720 50 > Johnny.out
	./YUVLoader Kimono1_1920x1080_24.yuv 1920 1080 50 > Kimono.out
	./YUVLoader ParkScene_1920x1080_24.yuv 1920 1080 50 > ParkScene.out
	./YUVLoader PartyScene_832x480_50.yuv 832 480 50 > PartyScene.out
	./YUVLoader PeopleOnStreet_2560x1600_30_crop.yuv 2560 1600 50 > PeopleOnStreet.out
	./YUVLoader RaceHorses_832x480_30.yuv 832 480 50 > RaceHorsesC.out
	./YUVLoader Traffic_2560x1600_30_crop.yuv 2560 1600 50 > Traffic.out
	echo TERMINADO

all: run
